version: 0.2
phases:
  install:
    commands:
      - npm install  # Example build commands
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'  # Include all files in the artifact
