version: 0.2
phases:
  install:
    commands:
      - cd /codebuild/output/src*/src  # Ensure this path matches the artifact structure
      - ls  # Verify the contents of the directory
      - npm install
  build:
    commands:
      - npm run build  # Adjust as per your build process
artifacts:
  files:
    - '**/*'  # Include all files in the artifact
