version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14  # Adjust to your Node.js version if applicable
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - echo "Build steps here"
      # Add commands to deploy your files to EC2 or other targets
artifacts:
  files:
    - '**/*'  # Include all necessary files for deployment
