version: 0.2
phases:
  install:
    commands:
      - cd /codebuild/output/src*/src
      - npm cache clean --force  # Clean npm cache
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
