version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - echo Dependencies installed.
  pre_build:
    commands:
      - echo Preparing build environment...
      - echo Environment prepared.
  build:
    commands:
      - echo Building the project...
      - echo "The build process goes here, e.g., mvn clean install for a Maven project"
  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'  # Adjust this pattern based on your project's file structure
  base-directory: 'build_output'  # Directory where the build output is stored
  discard-paths: yes  # Optional: Discards the path information of the files

cache:
  paths:
    - '/root/.m2/**/*'  # Example for Maven, adjust for your dependency manager
