version: 0.2
phases:
  install:
    commands:
      - cd /codebuild/output/src*/src  # Ensure this path matches the location of package.json
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
