version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Build steps here"
      # Add your build commands here if any
      # - npm run build

  post_build:
    commands:
      - echo "Starting deployment to EC2"
      - aws ssm get-parameter --name /my/secure/path/private-key --with-decryption --query Parameter.Value --output text > private-key.pem
      - chmod 600 private-key.pem
      - EC2_INSTANCE=ec2-user@your-ec2-instance-public-dns
      - ssh -o StrictHostKeyChecking=no -i private-key.pem $EC2_INSTANCE 'mkdir -p /var/www/html'
      - scp -o StrictHostKeyChecking=no -i private-key.pem -r ./dist/* $EC2_INSTANCE:/var/www/html/
      - ssh -o StrictHostKeyChecking=no -i private-key.pem $EC2_INSTANCE 'sudo systemctl restart myapp.service'

artifacts:
  files:
    - '**/*'
